### ISSUE TITLE
특정 운영체제에서 발생하는 `EmojiSelectModal` 그리드 이슈

### ISSUE THREAD

**Issue by FrontLeejonghun** [0xBono/bucketlist#13]
기존 윈도우에서 일어난 그리드 이슈를 gird auto fit 으로 해결 및 overflow 가독성을 위한 x,y 축 구분
기존 345 / 5 를하여 57.5px 로 고정 후 1fr 로 지정 하였습니다.

```css  
.emoji-list {
    display: grid;
    width: 100%;
    grid-template-columns: repeat(auto-fit, minmax(57.5px, 1fr));
    overflow-x: hidden;
    overflow-y: scroll;
    justify-content: center;
    margin-top: 8px;

    span {
      font-size: 40px;
      padding: 8px;
      cursor: pointer;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    &::-webkit-scrollbar {
      display: none;
    }
  }
```
